#!/bin/bash

# Initialize Machine-Specific Git Configuration - macOS and Linux
# Creates ~/.gitconfig.local with machine-specific paths, SSH commit signing,
# the HTTPS credential helper, and safe directories. The per-OS detection
# (credential helper, op-ssh-sign paths) lives in scripts/shared/platform.sh.
# The per-OS scripts in scripts/mac version/ and scripts/linux version/ are
# wrappers around this one.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../shared/functions.sh
source "$SCRIPT_DIR/../shared/functions.sh"
# shellcheck source=../shared/platform.sh
source "$SCRIPT_DIR/../shared/platform.sh"

FORCE=false
HELP=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force) FORCE=true; shift ;;
        -h|--help)  HELP=true;  shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ "$HELP" = true ]; then
    cat << 'HELP'
Initialize Machine-Specific Git Configuration - macOS and Linux

USAGE:
    scripts/unix/initialize-local-config.sh [OPTIONS]

OPTIONS:
    -f, --force     Overwrite existing .gitconfig.local without prompting
                    (the old file is kept as .gitconfig.local.bak.<timestamp>)
    -h, --help      Display this help message

DESCRIPTION:
    Creates ~/.gitconfig.local with machine-specific settings. This file is
    included by the main .gitconfig and should NOT be version controlled.
    - Global gitignore path
    - SSH commit signing: prefers an on-disk key file (~/.ssh/claude_desktop or
      ~/.ssh/id_ed25519_signing, with its .pub, and the optional
      ~/.ssh/git-sign-no-agent wrapper); falls back to 1Password's
      op-ssh-sign if installed; otherwise, if git already has a
      user.signingkey, writes allowedSignersFile so signatures verify
    - HTTPS credential helper: the macOS login keychain (osxkeychain) on
      macOS; the GitHub CLI (gh auth git-credential), else libsecret, on Linux
    - Safe directory entries (plus Homebrew's repo on a shared Mac where
      another account owns it)
HELP
    exit 0
fi

# Guard: the credential helper differs per OS, and the wrong platform's config
# breaks HTTPS auth: the macOS script once wrote credential.helper =
# osxkeychain on the Ubuntu server (issue #179). Run directly, this script
# targets the host; through a per-OS wrapper it refuses a host of the other
# kind. Tests set GITCONFIG_ALLOW_CROSS_OS=1 to run either platform's
# behaviour in a sandbox anywhere.
TARGET_OS="$(resolve_target_os script initialize-local-config.sh)" || exit 1
OS_NAME="$(os_display_name "$TARGET_OS")"

HOME_DIR="$HOME"
LOCAL_CONFIG_PATH="$HOME_DIR/.gitconfig.local"

echo "Git Local Configuration Setup ($OS_NAME)"
echo "======================================="
echo "Home Directory: $HOME_DIR"
echo "Local Config Path: $LOCAL_CONFIG_PATH"
echo ""

if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$FORCE" = false ]; then
    echo ".gitconfig.local already exists."
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

CONFIG_CONTENT="# Machine-Specific Git Configuration ($OS_NAME)
# Auto-generated by initialize-local-config.sh — do NOT commit this file

[core]
	excludesfile = $HOME_DIR/.gitignore_global
"

# --- SSH commit signing ------------------------------------------------------
detect_signing_key "$TARGET_OS" "$HOME_DIR"

SIGNING_ENABLED=false
case "$SIGNING_MODE" in
    file)
        # File-based key wins over op-ssh-sign: agent-based signing prompts for
        # Touch ID on every commit and hangs unattended runs (issue #171).
        echo "[INFO] Detected on-disk SSH signing key: $SIGNING_KEY_FILE"
        SIGNING_ENABLED=true
        CONFIG_CONTENT+="
[user]
	# Sign with the on-disk private key file — no SSH agent, no Touch ID
	# prompt. Must be the private key PATH (not the .pub): if the same key is
	# also loaded in an agent, ssh-keygen would route a .pub through it.
	signingkey = $SIGNING_KEY_FILE

[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers
"
        if [ -n "$SIGNING_PROGRAM" ]; then
            echo "[INFO] Using no-agent signing wrapper: $SIGNING_PROGRAM"
            CONFIG_CONTENT+="	# Sign via a wrapper that unsets SSH_AUTH_SOCK so ssh-keygen reads the
	# private key from disk instead of the 1Password agent (Touch ID prompt).
	program = $SIGNING_PROGRAM
"
        fi
        CONFIG_CONTENT+="
[commit]
	gpgsign = true
"
        ;;
    op)
        echo "[INFO] Detected 1Password SSH signing helper: $SIGNING_PROGRAM"
        SIGNING_ENABLED=true
        CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	program = $SIGNING_PROGRAM
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers

[commit]
	gpgsign = true
"
        ;;
    existing)
        # No key file and no op-ssh-sign, but git already has a signing key (the
        # template ships a literal one with commit.gpgsign = true, or the user
        # set one). Signing is on either way, so write allowedSignersFile or
        # verification reports "No signature" (issue #116). Omit the program.
        echo "[INFO] op-ssh-sign not found, but a signing key is configured:"
        echo "       $EXISTING_SIGNING_KEY"
        echo "       Writing allowedSignersFile so signatures verify locally."
        SIGNING_ENABLED=true
        CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers
"
        ;;
    *)
        echo "[INFO] No signing key found and op-ssh-sign not installed — skipping signing config."
        echo "       Preferred: create an on-disk key (~/.ssh/id_ed25519_signing), register it"
        echo "       on GitHub as a signing key, then re-run this script."
        if [ "$TARGET_OS" = macos ]; then
            echo "       Or install 1Password: brew install 1password-cli"
            CONFIG_CONTENT+="
# Uncomment and set program path to enable SSH commit signing:
# [gpg]
# 	format = ssh
# [gpg \"ssh\"]
# 	program = /opt/homebrew/bin/op-ssh-sign
# [commit]
# 	gpgsign = true
"
        else
            CONFIG_CONTENT+="
# Uncomment to enable file-based SSH commit signing:
# [user]
# 	signingkey = $HOME_DIR/.ssh/id_ed25519_signing
# [gpg]
# 	format = ssh
# [commit]
# 	gpgsign = true
"
        fi
        ;;
esac

# --- HTTPS credential helper -------------------------------------------------
# Without one, unattended git over HTTPS fails ("could not read Username for
# 'https://github.com'"), e.g. `bd dolt push` or scheduled pulls of private
# repos (issue #179). Every block starts with an empty `helper =` line:
# credential.helper is multi-valued and accumulates, so a stale helper from
# another config level would otherwise answer first (issues #180, #183).
detect_credential_helper "$TARGET_OS"
case "$CREDENTIAL_HELPER_KIND" in
    osxkeychain)
        CONFIG_CONTENT+="
[credential]
	# Lets unattended HTTPS pulls of private repos (e.g. the claude-skills
	# launchd sync) authenticate from the macOS login keychain — no prompt and
	# no 1Password dependency. Store a token once with:
	#   git credential-osxkeychain store
	# The empty helper line resets helpers inherited from other config levels:
	# credential.helper is multi-valued and accumulates, so a stale helper from
	# a migrated other-platform config would otherwise answer first (issue #183,
	# mirroring the Linux blocks from #180).
	helper =
	helper = osxkeychain
"
        ;;
    gh)
        echo "[INFO] Using GitHub CLI credential helper: $CREDENTIAL_HELPER_PATH"
        echo "       Run 'gh auth login' once if you haven't — the helper reads gh's token."
        CONFIG_CONTENT+="
[credential \"https://github.com\"]
	# HTTPS auth from the gh CLI token, so unattended git over HTTPS (e.g.
	# \`bd dolt push\`, cron pulls of private repos) never prompts. The empty
	# helper line resets any helpers inherited from other config levels.
	helper =
	helper = !$CREDENTIAL_HELPER_PATH auth git-credential

[credential \"https://gist.github.com\"]
	helper =
	helper = !$CREDENTIAL_HELPER_PATH auth git-credential
"
        ;;
    libsecret)
        echo "[INFO] Using libsecret credential helper: $CREDENTIAL_HELPER_PATH"
        CONFIG_CONTENT+="
[credential]
	# HTTPS auth from the desktop keyring via libsecret — no prompt once a
	# token has been stored (first interactive push/pull saves it). The empty
	# helper line resets any helpers inherited from other config levels, so a
	# stale one can't answer first with an expired credential (issue #179).
	helper =
	helper = $CREDENTIAL_HELPER_PATH
"
        ;;
    *)
        echo "[INFO] No credential helper found (gh CLI or libsecret) — skipping."
        echo "       Install the GitHub CLI (https://cli.github.com) and run 'gh auth login',"
        echo "       then re-run this script to enable unattended HTTPS auth."
        CONFIG_CONTENT+="
# Uncomment to enable HTTPS auth via the GitHub CLI (after 'gh auth login'):
# [credential \"https://github.com\"]
# 	helper =
# 	helper = !gh auth git-credential
"
        ;;
esac

# --- Safe directories --------------------------------------------------------
CONFIG_CONTENT+="
[safe]
	# Add trusted local or network directories here:
	# directory = /path/to/trusted/repo
	directory = $HOME_DIR/Documents/Scripts/gitconfig
"

# On a shared Mac, /opt/homebrew can be owned by a different account. git then
# refuses to read Homebrew's repo ("detected dubious ownership"), which breaks
# `brew update` with "fatal: not in a git directory". Trust the repo whenever
# it exists and belongs to someone else. HOMEBREW_REPO is overridable so tests
# can point it at a sandbox path.
if [ "$TARGET_OS" = macos ]; then
    HOMEBREW_REPO="${HOMEBREW_REPO:-/opt/homebrew}"
    if [ -d "$HOMEBREW_REPO/.git" ] && [ "$(file_owner_uid "$HOMEBREW_REPO")" != "$(id -u)" ]; then
        echo "[INFO] $HOMEBREW_REPO is owned by another user — adding it as a safe directory so brew update works."
        CONFIG_CONTENT+="	# Homebrew's repo is owned by another account on this shared machine;
	# without this entry git's dubious-ownership check breaks \`brew update\`.
	directory = $HOMEBREW_REPO
"
    fi
fi

# Keep a timestamped copy of the file we are about to replace, unless it
# already holds exactly what we would write.
if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$(cat "$LOCAL_CONFIG_PATH")" != "$(printf '%s\n' "$CONFIG_CONTENT")" ]; then
    backup_copy "$LOCAL_CONFIG_PATH"
fi

printf '%s\n' "$CONFIG_CONTENT" > "$LOCAL_CONFIG_PATH"
echo "[OK] Created .gitconfig.local"
echo ""

# When signing is enabled, register the signing identity so git can verify
# SSH commit signatures locally.
if [ "$SIGNING_ENABLED" = true ]; then
    update_allowed_signers "$HOME_DIR/.ssh/allowed_signers"
    echo ""
fi

echo "To add safe directories, edit: $LOCAL_CONFIG_PATH"
echo ""
