#!/bin/bash

# Initialize Machine-Specific Git Configuration - macOS Version
# Creates ~/.gitconfig.local with machine-specific paths and SSH signing config.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../shared/functions.sh
source "$SCRIPT_DIR/../shared/functions.sh"

FORCE=false
HELP=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force) FORCE=true; shift ;;
        -h|--help)  HELP=true;  shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ "$HELP" = true ]; then
    cat << 'EOF'
Initialize Machine-Specific Git Configuration - macOS Version

USAGE:
    ./initialize-local-config.sh [OPTIONS]

OPTIONS:
    -f, --force     Overwrite existing .gitconfig.local without prompting
    -h, --help      Display this help message

DESCRIPTION:
    Creates ~/.gitconfig.local with machine-specific settings including:
    - Global gitignore path
    - SSH commit signing via 1Password (op-ssh-sign), if installed
    - Safe directory entries
EOF
    exit 0
fi

HOME_DIR="$HOME"
LOCAL_CONFIG_PATH="$HOME_DIR/.gitconfig.local"

echo "Git Local Configuration Setup (macOS)"
echo "======================================="
echo "Home Directory: $HOME_DIR"
echo "Local Config Path: $LOCAL_CONFIG_PATH"
echo ""

if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$FORCE" = false ]; then
    echo ".gitconfig.local already exists."
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# Detect op-ssh-sign (1Password SSH signing helper)
OP_SSH_SIGN=""
if [ -x "/opt/homebrew/bin/op-ssh-sign" ]; then
    # Apple Silicon Homebrew path
    OP_SSH_SIGN="/opt/homebrew/bin/op-ssh-sign"
elif [ -x "/usr/local/bin/op-ssh-sign" ]; then
    # Intel Homebrew path
    OP_SSH_SIGN="/usr/local/bin/op-ssh-sign"
fi

# Build the config content
CONFIG_CONTENT="# Machine-Specific Git Configuration (macOS)
# Auto-generated by initialize-local-config.sh — do NOT commit this file

[core]
	excludesfile = $HOME_DIR/.gitignore_global
"

# A signing key may already be configured in git even without 1Password — e.g.
# the template ships a literal signingkey with commit.gpgsign=true, or a user
# points user.signingkey at a file-based key. In all of those cases signing is
# active, so allowedSignersFile must be written or git reports "No signature"
# on verification. Mirror the Linux behavior: whenever signing is enabled, write
# the [gpg "ssh"] allowedSignersFile block.
EXISTING_SIGNING_KEY="$(git config --get user.signingkey 2>/dev/null || true)"

SIGNING_ENABLED=false
if [ -n "$OP_SSH_SIGN" ]; then
    echo "[INFO] Detected 1Password SSH signing helper: $OP_SSH_SIGN"
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	program = $OP_SSH_SIGN
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers

[commit]
	gpgsign = true
"
elif [ -n "$EXISTING_SIGNING_KEY" ]; then
    # op-ssh-sign isn't installed, but a signing key is already configured
    # (file-based key or a literal public key). Still write allowedSignersFile
    # so signatures verify locally; omit the 1Password program line.
    echo "[INFO] op-ssh-sign not found, but a signing key is configured:"
    echo "       $EXISTING_SIGNING_KEY"
    echo "       Writing allowedSignersFile so signatures verify locally."
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers
"
else
    echo "[INFO] op-ssh-sign not found and no signing key configured — skipping signing config."
    echo "       Install 1Password CLI via Homebrew to enable commit signing:"
    echo "         brew install 1password-cli"
    CONFIG_CONTENT+="
# Uncomment and set program path to enable SSH commit signing:
# [gpg]
# 	format = ssh
# [gpg \"ssh\"]
# 	program = /opt/homebrew/bin/op-ssh-sign
# [commit]
# 	gpgsign = true
"
fi

CONFIG_CONTENT+="
[safe]
	# Add trusted local or network directories here:
	# directory = /path/to/trusted/repo
	directory = $HOME_DIR/Documents/Scripts/gitconfig
"

printf '%s\n' "$CONFIG_CONTENT" > "$LOCAL_CONFIG_PATH"
echo "[OK] Created .gitconfig.local"
echo ""

# When signing is enabled, register the signing identity so git can verify
# SSH commit signatures locally.
if [ "$SIGNING_ENABLED" = true ]; then
    update_allowed_signers "$HOME_DIR/.ssh/allowed_signers"
    echo ""
fi

echo "To add safe directories, edit: $LOCAL_CONFIG_PATH"
echo ""
