#!/bin/bash

# Initialize Machine-Specific Git Configuration - macOS Version
# Creates ~/.gitconfig.local with machine-specific paths and SSH signing config.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../shared/functions.sh
source "$SCRIPT_DIR/../shared/functions.sh"

FORCE=false
HELP=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force) FORCE=true; shift ;;
        -h|--help)  HELP=true;  shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ "$HELP" = true ]; then
    cat << 'EOF'
Initialize Machine-Specific Git Configuration - macOS Version

USAGE:
    ./initialize-local-config.sh [OPTIONS]

OPTIONS:
    -f, --force     Overwrite existing .gitconfig.local without prompting
    -h, --help      Display this help message

DESCRIPTION:
    Creates ~/.gitconfig.local with machine-specific settings including:
    - Global gitignore path
    - SSH commit signing: prefers an on-disk key file (~/.ssh/claude_desktop or
      ~/.ssh/id_ed25519_signing, with the optional git-sign-no-agent wrapper);
      falls back to 1Password (op-ssh-sign) if installed
    - Safe directory entries
EOF
    exit 0
fi

HOME_DIR="$HOME"
LOCAL_CONFIG_PATH="$HOME_DIR/.gitconfig.local"

echo "Git Local Configuration Setup (macOS)"
echo "======================================="
echo "Home Directory: $HOME_DIR"
echo "Local Config Path: $LOCAL_CONFIG_PATH"
echo ""

if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$FORCE" = false ]; then
    echo ".gitconfig.local already exists."
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# Detect an on-disk file-based signing key. This is the preferred setup: git
# signs via ssh-keygen straight from the file — no SSH agent, no Touch ID
# prompt, works unattended. Both the private key and its .pub must exist (the
# .pub feeds allowed_signers); otherwise fall through to the other branches.
SIGNING_KEY_FILE=""
for candidate in "$HOME_DIR/.ssh/claude_desktop" "$HOME_DIR/.ssh/id_ed25519_signing"; do
    if [ -f "$candidate" ] && [ -f "$candidate.pub" ]; then
        SIGNING_KEY_FILE="$candidate"
        break
    fi
done

# Optional companion wrapper: unsets SSH_AUTH_SOCK so ssh-keygen signs from
# disk even when the same key is loaded in the 1Password agent (which would
# otherwise prompt for Touch ID on every commit).
NO_AGENT_WRAPPER="$HOME_DIR/.ssh/git-sign-no-agent"

# Detect op-ssh-sign (1Password SSH signing helper)
OP_SSH_SIGN=""
if [ -x "/opt/homebrew/bin/op-ssh-sign" ]; then
    # Apple Silicon Homebrew path
    OP_SSH_SIGN="/opt/homebrew/bin/op-ssh-sign"
elif [ -x "/usr/local/bin/op-ssh-sign" ]; then
    # Intel Homebrew path
    OP_SSH_SIGN="/usr/local/bin/op-ssh-sign"
fi

# Build the config content
CONFIG_CONTENT="# Machine-Specific Git Configuration (macOS)
# Auto-generated by initialize-local-config.sh — do NOT commit this file

[core]
	excludesfile = $HOME_DIR/.gitignore_global
"

# A signing key may already be configured in git even without 1Password — e.g.
# the template ships a literal signingkey with commit.gpgsign=true, or a user
# points user.signingkey at a file-based key. In all of those cases signing is
# active, so allowedSignersFile must be written or git reports "No signature"
# on verification. Mirror the Linux behavior: whenever signing is enabled, write
# the [gpg "ssh"] allowedSignersFile block.
EXISTING_SIGNING_KEY="$(git config --get user.signingkey 2>/dev/null || true)"

SIGNING_ENABLED=false
if [ -n "$SIGNING_KEY_FILE" ]; then
    # File-based key wins over op-ssh-sign: agent-based signing prompts for
    # Touch ID on every commit and hangs unattended runs (issue #171).
    echo "[INFO] Detected on-disk SSH signing key: $SIGNING_KEY_FILE"
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[user]
	# Sign with the on-disk private key file — no SSH agent, no Touch ID
	# prompt. Must be the private key PATH (not the .pub): if the same key is
	# also loaded in an agent, ssh-keygen would route a .pub through it.
	signingkey = $SIGNING_KEY_FILE

[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers
"
    if [ -x "$NO_AGENT_WRAPPER" ]; then
        echo "[INFO] Using no-agent signing wrapper: $NO_AGENT_WRAPPER"
        CONFIG_CONTENT+="	# Sign via a wrapper that unsets SSH_AUTH_SOCK so ssh-keygen reads the
	# private key from disk instead of the 1Password agent (Touch ID prompt).
	program = $NO_AGENT_WRAPPER
"
    fi
    CONFIG_CONTENT+="
[commit]
	gpgsign = true
"
elif [ -n "$OP_SSH_SIGN" ]; then
    echo "[INFO] Detected 1Password SSH signing helper: $OP_SSH_SIGN"
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	program = $OP_SSH_SIGN
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers

[commit]
	gpgsign = true
"
elif [ -n "$EXISTING_SIGNING_KEY" ]; then
    # op-ssh-sign isn't installed, but a signing key is already configured
    # (file-based key or a literal public key). Still write allowedSignersFile
    # so signatures verify locally; omit the 1Password program line.
    echo "[INFO] op-ssh-sign not found, but a signing key is configured:"
    echo "       $EXISTING_SIGNING_KEY"
    echo "       Writing allowedSignersFile so signatures verify locally."
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers
"
else
    echo "[INFO] No signing key found and op-ssh-sign not installed — skipping signing config."
    echo "       Preferred: create an on-disk key (~/.ssh/id_ed25519_signing), register it"
    echo "       on GitHub as a signing key, then re-run this script. Or install 1Password:"
    echo "         brew install 1password-cli"
    CONFIG_CONTENT+="
# Uncomment and set program path to enable SSH commit signing:
# [gpg]
# 	format = ssh
# [gpg \"ssh\"]
# 	program = /opt/homebrew/bin/op-ssh-sign
# [commit]
# 	gpgsign = true
"
fi

CONFIG_CONTENT+="
[credential]
	# Lets unattended HTTPS pulls of private repos (e.g. the claude-skills
	# launchd sync) authenticate from the macOS login keychain — no prompt and
	# no 1Password dependency. Store a token once with:
	#   git credential-osxkeychain store
	helper = osxkeychain
"

CONFIG_CONTENT+="
[safe]
	# Add trusted local or network directories here:
	# directory = /path/to/trusted/repo
	directory = $HOME_DIR/Documents/Scripts/gitconfig
"

# On a shared Mac, /opt/homebrew can be owned by a different account. git then
# refuses to read Homebrew's repo ("detected dubious ownership"), which breaks
# `brew update` with "fatal: not in a git directory". Trust the repo whenever
# it exists and belongs to someone else. HOMEBREW_REPO is overridable so tests
# can point it at a sandbox path.
HOMEBREW_REPO="${HOMEBREW_REPO:-/opt/homebrew}"
if [ -d "$HOMEBREW_REPO/.git" ] && [ "$(file_owner_uid "$HOMEBREW_REPO")" != "$(id -u)" ]; then
    echo "[INFO] $HOMEBREW_REPO is owned by another user — adding it as a safe directory so brew update works."
    CONFIG_CONTENT+="	# Homebrew's repo is owned by another account on this shared machine;
	# without this entry git's dubious-ownership check breaks \`brew update\`.
	directory = $HOMEBREW_REPO
"
fi

printf '%s\n' "$CONFIG_CONTENT" > "$LOCAL_CONFIG_PATH"
echo "[OK] Created .gitconfig.local"
echo ""

# When signing is enabled, register the signing identity so git can verify
# SSH commit signatures locally.
if [ "$SIGNING_ENABLED" = true ]; then
    update_allowed_signers "$HOME_DIR/.ssh/allowed_signers"
    echo ""
fi

echo "To add safe directories, edit: $LOCAL_CONFIG_PATH"
echo ""
