#!/bin/bash

# Initialize Machine-Specific Git Configuration - Linux/Unix Version
# This script creates ~/.gitconfig.local with machine-specific paths and safe directories
# Usage: ./initialize-local-config.sh [OPTIONS]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../shared/functions.sh
source "$SCRIPT_DIR/../shared/functions.sh"

FORCE=false
HELP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        -h|--help)
            HELP=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ "$HELP" = true ]; then
    cat << 'EOF'
Initialize Machine-Specific Git Configuration - Linux/Unix Version

USAGE:
    ./initialize-local-config.sh [OPTIONS]

OPTIONS:
    -f, --force     Overwrite existing .gitconfig.local without prompting
    -h, --help      Display this help message

DESCRIPTION:
    Creates ~/.gitconfig.local with machine-specific safe directories and paths.
    This file is included by the main .gitconfig and should NOT be version controlled.

SAFE DIRECTORIES:
    Add network locations and local paths that git should trust.
    Common examples:
    - Network mounts (e.g., /mnt/shared)
    - Local development directories
    - Work-specific repositories

EXAMPLE:
    # Interactive mode (prompts before overwriting)
    ./initialize-local-config.sh

    # Force mode (overwrites without prompting)
    ./initialize-local-config.sh --force
EOF
    exit 0
fi

# Guard: this script writes Linux-specific config. Running the wrong platform's
# script mislabels ~/.gitconfig.local — the macOS one applied credential.helper
# = osxkeychain on the Ubuntu server and broke all HTTPS git auth (issue #179).
# Tests set GITCONFIG_ALLOW_CROSS_OS=1 to run the script in a sandbox anywhere.
if [ "$(uname -s)" = "Darwin" ] && [ "${GITCONFIG_ALLOW_CROSS_OS:-0}" != "1" ]; then
    echo "[ERROR] This is the Linux script but this host is macOS." >&2
    echo "        Use 'scripts/mac version/initialize-local-config.sh' instead," >&2
    echo "        or set GITCONFIG_ALLOW_CROSS_OS=1 to override (tests/sandboxes)." >&2
    exit 1
fi

HOME_DIR="$HOME"
LOCAL_CONFIG_PATH="$HOME_DIR/.gitconfig.local"

echo "Git Local Configuration Setup"
echo "================================"
echo "Home Directory: $HOME_DIR"
echo "Local Config Path: $LOCAL_CONFIG_PATH"
echo ""

# Check if .gitconfig.local already exists
if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$FORCE" = false ]; then
    echo ".gitconfig.local already exists."
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# Detect file-based SSH signing key (used on headless servers without 1Password desktop)
SIGNING_KEY_PATH="$HOME_DIR/.ssh/id_ed25519_signing"

CONFIG_CONTENT="# Machine-Specific Git Configuration (Linux)
# Auto-generated by initialize-local-config.sh — do NOT commit this file

[core]
	excludesfile = $HOME_DIR/.gitignore_global
"

SIGNING_ENABLED=false
if [ -f "$SIGNING_KEY_PATH" ]; then
    echo "[INFO] Detected SSH signing key: $SIGNING_KEY_PATH"
    SIGNING_ENABLED=true
    CONFIG_CONTENT+="
[user]
	signingKey = $SIGNING_KEY_PATH

[gpg]
	format = ssh

[gpg \"ssh\"]
	# Lets git verify SSH commit signatures locally (git log --show-signature)
	allowedSignersFile = $HOME_DIR/.ssh/allowed_signers

[commit]
	gpgsign = true
"
else
    echo "[INFO] SSH signing key not found at $SIGNING_KEY_PATH — skipping signing config."
    echo "       To enable commit signing, create ~/.ssh/id_ed25519_signing and register"
    echo "       it as a signing key on GitHub, then re-run this script."
    CONFIG_CONTENT+="
# Uncomment to enable file-based SSH commit signing:
# [user]
# 	signingKey = $HOME_DIR/.ssh/id_ed25519_signing
# [gpg]
# 	format = ssh
# [commit]
# 	gpgsign = true
"
fi

# HTTPS credential helper (issue #179). Without one, unattended git over HTTPS
# fails ("could not read Username for 'https://github.com'") — e.g. `bd dolt push`
# or cron pulls of private repos. Prefer the GitHub CLI helper (token managed by
# `gh auth login`, scoped to github.com like `gh auth setup-git` does); fall back
# to libsecret where a distro ships it; otherwise leave a commented hint.
# GITCONFIG_GH_BIN / GITCONFIG_LIBSECRET_BIN are test seams (like HOMEBREW_REPO
# in the macOS script): set to a path to force that helper, set to the empty
# string to simulate "not installed". Unset means autodetect.
if [ -n "${GITCONFIG_GH_BIN+set}" ]; then
    GH_PATH="$GITCONFIG_GH_BIN"
else
    GH_PATH="$(command -v gh 2>/dev/null || true)"
fi

if [ -n "${GITCONFIG_LIBSECRET_BIN+set}" ]; then
    LIBSECRET_HELPER="$GITCONFIG_LIBSECRET_BIN"
else
    LIBSECRET_HELPER="$(command -v git-credential-libsecret 2>/dev/null || true)"
    if [ -z "$LIBSECRET_HELPER" ]; then
        # Some distros ship the helper in git's exec path without a PATH entry.
        GIT_EXEC_PATH_DIR="$(git --exec-path 2>/dev/null || true)"
        if [ -n "$GIT_EXEC_PATH_DIR" ] && [ -x "$GIT_EXEC_PATH_DIR/git-credential-libsecret" ]; then
            LIBSECRET_HELPER="$GIT_EXEC_PATH_DIR/git-credential-libsecret"
        fi
    fi
fi

if [ -n "$GH_PATH" ]; then
    echo "[INFO] Using GitHub CLI credential helper: $GH_PATH"
    echo "       Run 'gh auth login' once if you haven't — the helper reads gh's token."
    CONFIG_CONTENT+="
[credential \"https://github.com\"]
	# HTTPS auth from the gh CLI token, so unattended git over HTTPS (e.g.
	# \`bd dolt push\`, cron pulls of private repos) never prompts. The empty
	# helper line resets any helpers inherited from other config levels.
	helper =
	helper = !$GH_PATH auth git-credential

[credential \"https://gist.github.com\"]
	helper =
	helper = !$GH_PATH auth git-credential
"
elif [ -n "$LIBSECRET_HELPER" ]; then
    echo "[INFO] Using libsecret credential helper: $LIBSECRET_HELPER"
    CONFIG_CONTENT+="
[credential]
	# HTTPS auth from the desktop keyring via libsecret — no prompt once a
	# token has been stored (first interactive push/pull saves it). The empty
	# helper line resets any helpers inherited from other config levels, so a
	# stale one can't answer first with an expired credential (issue #179).
	helper =
	helper = $LIBSECRET_HELPER
"
else
    echo "[INFO] No credential helper found (gh CLI or libsecret) — skipping."
    echo "       Install the GitHub CLI (https://cli.github.com) and run 'gh auth login',"
    echo "       then re-run this script to enable unattended HTTPS auth."
    CONFIG_CONTENT+="
# Uncomment to enable HTTPS auth via the GitHub CLI (after 'gh auth login'):
# [credential \"https://github.com\"]
# 	helper =
# 	helper = !gh auth git-credential
"
fi

CONFIG_CONTENT+="
[safe]
	# Add trusted local or network directories here:
	# directory = /path/to/trusted/repo
	directory = $HOME_DIR/Documents/Scripts/gitconfig
"

printf '%s\n' "$CONFIG_CONTENT" > "$LOCAL_CONFIG_PATH"
echo "[OK] Created .gitconfig.local"
echo ""

# When signing is enabled, register the signing identity so git can verify
# SSH commit signatures locally.
if [ "$SIGNING_ENABLED" = true ]; then
    update_allowed_signers "$HOME_DIR/.ssh/allowed_signers"
    echo ""
fi

echo "To add safe directories, edit: $LOCAL_CONFIG_PATH"
echo ""
