#!/bin/bash

# Initialize Machine-Specific Git Configuration - Linux/Unix Version
# This script creates ~/.gitconfig.local with machine-specific paths and safe directories
# Usage: ./initialize-local-config.sh [OPTIONS]

set -e

FORCE=false
HELP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        -h|--help)
            HELP=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ "$HELP" = true ]; then
    cat << 'EOF'
Initialize Machine-Specific Git Configuration - Linux/Unix Version

USAGE:
    ./initialize-local-config.sh [OPTIONS]

OPTIONS:
    -f, --force     Overwrite existing .gitconfig.local without prompting
    -h, --help      Display this help message

DESCRIPTION:
    Creates ~/.gitconfig.local with machine-specific safe directories and paths.
    This file is included by the main .gitconfig and should NOT be version controlled.

SAFE DIRECTORIES:
    Add network locations and local paths that git should trust.
    Common examples:
    - Network mounts (e.g., /mnt/shared)
    - Local development directories
    - Work-specific repositories

EXAMPLE:
    # Interactive mode (prompts before overwriting)
    ./initialize-local-config.sh

    # Force mode (overwrites without prompting)
    ./initialize-local-config.sh --force
EOF
    exit 0
fi

HOME_DIR="$HOME"
LOCAL_CONFIG_PATH="$HOME_DIR/.gitconfig.local"

echo "Git Local Configuration Setup"
echo "================================"
echo "Home Directory: $HOME_DIR"
echo "Local Config Path: $LOCAL_CONFIG_PATH"
echo ""

# Check if .gitconfig.local already exists
if [ -f "$LOCAL_CONFIG_PATH" ] && [ "$FORCE" = false ]; then
    echo ".gitconfig.local already exists."
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# Detect file-based SSH signing key (used on headless servers without 1Password desktop)
SIGNING_KEY_PATH="$HOME_DIR/.ssh/id_ed25519_signing"

CONFIG_CONTENT="# Machine-Specific Git Configuration (Linux)
# Auto-generated by initialize-local-config.sh — do NOT commit this file

[core]
	excludesfile = $HOME_DIR/.gitignore_global
"

if [ -f "$SIGNING_KEY_PATH" ]; then
    echo "[INFO] Detected SSH signing key: $SIGNING_KEY_PATH"
    CONFIG_CONTENT+="
[user]
	signingKey = $SIGNING_KEY_PATH

[gpg]
	format = ssh

[commit]
	gpgsign = true
"
else
    echo "[INFO] SSH signing key not found at $SIGNING_KEY_PATH — skipping signing config."
    echo "       To enable commit signing, create ~/.ssh/id_ed25519_signing and register"
    echo "       it as a signing key on GitHub, then re-run this script."
    CONFIG_CONTENT+="
# Uncomment to enable file-based SSH commit signing:
# [user]
# 	signingKey = $HOME_DIR/.ssh/id_ed25519_signing
# [gpg]
# 	format = ssh
# [commit]
# 	gpgsign = true
"
fi

CONFIG_CONTENT+="
[safe]
	# Add trusted local or network directories here:
	# directory = /path/to/trusted/repo
	directory = $HOME_DIR/Documents/Scripts/gitconfig
"

printf '%s\n' "$CONFIG_CONTENT" > "$LOCAL_CONFIG_PATH"
echo "[OK] Created .gitconfig.local"
echo ""
echo "To add safe directories, edit: $LOCAL_CONFIG_PATH"
echo ""
